# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 17:28
from __future__ import unicode_literals

from django.db import migrations, models
from django.utils import timezone



class Migration(migrations.Migration):

    dependencies = [
        ('iron_bank_api', '0002_auto_20161028_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='created_by',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now()),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='process_type',
            field=models.CharField(choices=[('W', 'withdrawal'), ('D', 'deposit')], max_length=1),
        ),
    ]
