# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iron_bank_api', '0004_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='created_by',
            new_name='created',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='process_type',
            field=models.CharField(choices=[('W', 'Withdrawal'), ('D', 'Deposit')], max_length=1),
        ),
    ]
